# Generated by Django 6.0.4 on 2026-04-15 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat_hang', models.DateTimeField(auto_now_add=True)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('trang_thai', models.CharField(default='Chờ xử lý', max_length=50)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chuc_vu', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(max_length=255)),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=10)),
                ('la_san_pham_moi', models.BooleanField(default=True)),
                ('la_san_pham_noi_bat', models.BooleanField(default=False)),
                ('loai_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.loaihang')),
            ],
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_nhap', models.IntegerField()),
                ('ngay_nhap', models.DateTimeField(auto_now_add=True)),
                ('nhan_vien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.nhanvien')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('san_pham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_app.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_mua', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=10)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.donhang')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.sanpham')),
            ],
        ),
    ]
