# Generated by Django 6.0.4 on 2026-04-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='hinh_anh',
            field=models.ImageField(blank=True, null=True, upload_to='san_pham/'),
        ),
    ]
