# Generated by Django 6.0.4 on 2026-04-15 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_sanpham_hinh_anh'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='da_xac_thuc_lan_dau',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='ma_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_app.nhanvien'),
        ),
    ]
