# Generated by Django 6.0.4 on 2026-04-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_phieunhap_chitietphieunhap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='mo_ta_chi_tiet',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chi tiết'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='mo_ta_ngan',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn'),
        ),
        migrations.AddField(
            model_name='sanpham',
            name='uu_dai',
            field=models.TextField(blank=True, null=True, verbose_name='Ưu đãi đặc biệt'),
        ),
        migrations.CreateModel(
            name='HinhAnhSanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hinh_anh', models.ImageField(upload_to='san_pham_gallery/')),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_app.sanpham')),
            ],
        ),
    ]
