# Generated by Django 6.0.4 on 2026-04-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_sanpham_mo_ta_chi_tiet_sanpham_mo_ta_ngan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khachhang',
            name='da_xac_thuc_lan_dau',
        ),
        migrations.RemoveField(
            model_name='khachhang',
            name='ma_otp',
        ),
        migrations.AddField(
            model_name='khachhang',
            name='ho_ten',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ tên'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='dia_chi',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ giao hàng'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại'),
        ),
    ]
