# Generated by Django 6.0.4 on 2026-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0008_donhang_nhan_vien_tao'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='ghi_chu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
