# Generated by Django 6.0.4 on 2026-04-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_donhang_ghi_chu'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaihang',
            name='ma_loai',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mã loại'),
        ),
    ]
